### ISSUE TITLE
division of zero by zero or infinity by infinity

### ISSUE THREAD

**Issue by archfish** [turnon/elastalarm#2]
当查询无匹配数据返回时，出现异常

```log
resp: &{ {0 []} []}
panic: division of zero by zero or infinity by infinity

goroutine 38 [running]:
math/big.(*Float).Quo(0xc000199d98, 0xc000111260, 0xc000111230, 0x12fa4e0)
	/usr/local/Cellar/go/1.11.4/libexec/src/math/big/float.go:1643 +0x137
github.com/turnon/elastalarm/paradigms.(*Spike).Found(0xc000124960, 0xc000158370, 0x85, 0x600)
	github.com/turnon/elastalarm/paradigms/spike.go:80 +0x17a
main.(*monitor)._check(0xc000110c00, 0x0, 0x0)
	github.com/turnon/elastalarm/monitor.go:98 +0x2bc
main.(*monitor).check(0xc000110c00)
	github.com/turnon/elastalarm/monitor.go:62 +0x2f
main.(*monitor).run.func1(0xc000110c00)
	github.com/turnon/elastalarm/monitor.go:48 +0x40
created by main.(*monitor).run
	github.com/turnon/elastalarm/monitor.go:47 +0x3f
```

**Comment by turnon** [comment]
已改：可设置reference参数。

正常会以`current_doc_count / past__doc_count`计算变化幅度；

当`past__doc_count`为零时，以`current_doc_count / reference`计算；

若`reference`未设置或也为零，则不报警
